let quote_list = [
    ["The best way to predict the future is to create it.", "Peter Drucker"],
    ["Life is 10% what happens to us and 90% how we react to it.", "Charles R. Swindoll"],
    ["Do not wait to strike till the iron is hot; but make it hot by striking.", "William Butler Yeats"],
    ["The only limit to our realization of tomorrow is our doubts of today.", "Franklin D. Roosevelt"],
    ["In the middle of every difficulty lies opportunity.", "Albert Einstein"],
    ["Success is not final, failure is not fatal: It is the courage to continue that counts.", "Winston Churchill"],
    ["Do what you can, with what you have, where you are.", "Theodore Roosevelt"],
    ["Happiness depends upon ourselves.", "Aristotle"],
    ["Dream big and dare to fail.", "Norman Vaughan"],
    ["It does not matter how slowly you go as long as you do not stop.", "Confucius"],
    ["The harder the conflict, the greater the triumph.", "George Washington"],
    ["Believe you can and you're halfway there.", "Theodore Roosevelt"],
    ["Keep your face always toward the sunshine—and shadows will fall behind you.", "Walt Whitman"],
    ["What we achieve inwardly will change outer reality.", "Plutarch"],
    ["Do one thing every day that scares you.", "Eleanor Roosevelt"],
    ["Action is the foundational key to all success.", "Pablo Picasso"],
    ["Quality is not an act, it is a habit.", "Aristotle"],
    ["The mind is everything. What you think you become.", "Buddha"],
    ["Everything you’ve ever wanted is on the other side of fear.", "George Addair"],
    ["Fall seven times and stand up eight.", "Japanese Proverb"],
    ["Do not go where the path may lead, go instead where there is no path and leave a trail.", "Ralph Waldo Emerson"],
    ["The journey of a thousand miles begins with one step.", "Lao Tzu"],
    ["You miss 100% of the shots you don’t take.", "Wayne Gretzky"],
    ["If you want to lift yourself up, lift up someone else.", "Booker T. Washington"],
    ["It always seems impossible until it’s done.", "Nelson Mandela"],
    ["Don’t watch the clock; do what it does. Keep going.", "Sam Levenson"],
    ["Believe in yourself and all that you are.", "Christian D. Larson"],
    ["Small deeds done are better than great deeds planned.", "Peter Marshall"],
    ["A year from now you may wish you had started today.", "Karen Lamb"],
    ["Never bend your head. Always hold it high.", "Helen Keller"],
    ["Keep your eyes on the stars, and your feet on the ground.", "Theodore Roosevelt"],
    ["Strive not to be a success, but rather to be of value.", "Albert Einstein"],
    ["Happiness is not something ready made. It comes from your own actions.", "Dalai Lama"],
    ["The secret of getting ahead is getting started.", "Mark Twain"],
    ["Courage is resistance to fear, mastery of fear, not absence of fear.", "Mark Twain"],
    ["Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.", "Roy T. Bennett"],
    ["Do not let what you cannot do interfere with what you can do.", "John Wooden"],
    ["Opportunities don’t happen. You create them.", "Chris Grosser"],
    ["Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"],
    ["Your time is limited, so don’t waste it living someone else’s life.", "Steve Jobs"],
    ["Don’t be afraid to give up the good to go for the great.", "John D. Rockefeller"],
    ["I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"],
    ["You can’t cross the sea merely by standing and staring at the water.", "Rabindranath Tagore"],
    ["Great minds discuss ideas; average minds discuss events; small minds discuss people.", "Eleanor Roosevelt"],
    ["In the end, we only regret the chances we didn’t take.", "Lewis Carroll"],
    ["Act as if what you do makes a difference. It does.", "William James"],
    ["Don’t limit your challenges. Challenge your limits.", "Anonymous"],
    ["Start where you are. Use what you have. Do what you can.", "Arthur Ashe"],
    ["The future depends on what you do today.", "Mahatma Gandhi"],
    ["Everything has beauty, but not everyone sees it.", "Confucius"],
    ["Life is what happens when you’re busy making other plans.", "John Lennon"],
    ["The purpose of our lives is to be happy.", "Dalai Lama"]
  ];
  
showQuote();
function showQuote(){
    let random=Math.floor(Math.random()*quote_list.length)
    // let index=quote_list[random]
    document.querySelector('#quote').innerHTML=quote_list[random][0]
    document.querySelector('#author').innerHTML=quote_list[random][1]
}